services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Nelmio\ApiDocBundle\Render\RenderOpenApi: '@nelmio_api_doc.render_docs'

  
    Nelmio\ApiDocBundle\Controller\SwaggerUiController:
        arguments:
            $renderOpenApi: '@Nelmio\ApiDocBundle\Render\RenderOpenApi'
            $uiRenderer: 'swagger_ui'
        public: true
